### PR TITLE
DPSyn

### PR DESCRIPTION
**Pull request by Zhangzhk0819**
Create DPSyn project, including source code, code guide, algrithm description and README.md

### CODE REVIEW

**Comment by jnear** [comment]
Thank you for the submission! I'm a moderator helping to review PRs. We've identified a few potential changes that would help your submission fit in better with the collab space:

 - Would you like to list a specific open-source license in your README.md? Any license accepted by the OSI is allowed for entries in the collab space.
   
 - It would be helpful to include some instructions for users to run your code. Could you add a bit of documentation which describes how to run your tool on a simple example, either in README.md or in a separate file?

If you can make these changes to the PR, we'll get it merged in right away. Thanks!

**Comment by Zhangzhk0819** [comment]
Hi,
Thanks for the helpful comments. I have added the LICENSE file in the root path under MIT license. Also, I have added a paragraph in the document/README.md file to illustrate how to run our code.

**Comment by jnear** [comment]
Looks good to me - thank you!

**Comment by kboeckl** [comment]
For your particular thoughts: I pulled some details from your readme to describe your submission on our index file of challenge contributions. Let me know if I should adjust aspects of it:
https://github.com/usnistgov/PrivacyEngCollabSpace/blob/master/tools/de-identification/Differential-Privacy-Synthetic-Data-Challenge-Algorithms/README.md

**Pull request merged**
