### PR TITLE
gardn999 - Differential Privacy Synthetic Data Challenge Algorithm

### PR DESCRIPTION
**Pull request by gardn999**
This is the open source submission for gardn999 which received fourth place in the Differential Privacy Synthetic Data Challenge.

### CODE REVIEW

**Comment by jnear** [comment]
Thank you for the submission! I'm a moderator helping to review PRs. Everything looks good except for three minor points:

 - Does your algorithm have a descriptive name (apart from your team name in the synthetic data challenge)? Most of the tools in the collab space are associated with names specific to the tool (rather than the team which produced them).

 - We generally prefer not to have binaries included in the collab space. It looks like your binaries (jar and class files) can be compiled from the included source with `compile.sh`. Since they can be reconstructed from the source, could you remove the jar and class files from the PR?

 - Would you like to list a specific open-source license in your README.md? Any license accepted by the OSI is allowed for entries in the collab space.
   
Once these are taken care of, we will merge the PR. Thank you!

**Comment by gardn999** [comment]
changes:
- new contribution name: DPFieldGroups
- moved everything to DPFieldGroups folder
- removed class folder and jar file and set docker to compile before running each time
- added 3-Clause BSD license information to the end of README.md

**Comment by jnear** [comment]
Looks good to me - thank you!

**Comment by jnear** [comment]
One more question @gardn999 - could you add a short (e.g. 2-3 sentences, or a paragraph max) description of the high-level approach your algorithm takes? I've just realized that the `README.md` doesn't have a description like this, and it would be very helpful to have one. Thanks!

**Comment by gardn999** [comment]
Added a high-level approach description to README.md.

**Pull request merged**
